const x = 10

try{
    x = 23
}catch(err){
    console.log(`Erro: ${err}`)
}